<?php
/**
 * Return the default options of the theme
 * 
 * @return  void
 */

function themesflat_customize_default($key) {
	$default = array(
		'social_links'	=> array ("facebook-f" => '#',"instagram" => '#', "twitter" => '#', "dribbble" => '#' ),
		'show_social_share' => 0,		
		'social_footer' => 0,
		'go_top' => 1,
		'topbar_background_color'	=> '#1C1E22',
		'topbar_textcolor'	=> 'rgba(255, 255, 255, 0.7)',
		'topbar_link_color' => 'rgba(255, 255, 255, 0.3)',
		'topbar_link_color_hover' => '#FF4040',
		'topbar_show' => 0,
		'topbar_address_label' => '<i class="fas fa-map-marker-alt"></i>',
		'topbar_address' => '1247/Plot No. 39, 15th Phase, New York.',
		'topbar_email_label' => '',
		'topbar_email' => 'hello.creativemela.com ',
		'social_topbar' => 1,
		'typography_topbar' => array(
			'family' => 'Jost',
			'style'  => '400',
			'size'   => '14',
			'line_height'=>'1.5',
			'letter_spacing' => '',
		),
		'topbar_controls' => array('padding-top' => 15,'padding-bottom' => 15),
		'logo_controls' => array('padding-top' => '','padding-bottom' => ''),
		'style_header'	=> 'header-default',	
		'header_backgroundcolor'=>'rgba(255,255,255,0)',
		'header_sticky' => 1,
		'header_search_box' => 1,
		'header_content_right' => '',
		'header_absolute'	=> 1,
		'social_header' => 0,		
		'header_sidebar_toggler' => 0,
		'header_button_text' => '',
		'header_button_url' => '',
		'header_info_phone_text' => '',
		'header_info_phone_number' => '',
		'header_cart_icon' => 0,
		'header_wishlist_icon' => 0,
		'show_post_navigator' => 0,
		'show_entry_footer_content'	=> 1,
		'logo_width' => 170,
		'menu_location_primary' => 'primary',
		'site_logo'	=> THEMESFLAT_LINK . 'images/logo.png',
		'site_logo_mobile'	=> THEMESFLAT_LINK . 'images/logo.png',	
		'show_bottom' => 1,		
		'header_backgroundcolor_sticky'=>'#000',		
		'primary_color'=>'#04091D',
		'secondary_color'=>'#FF4040',
		'accent_color'=>'#222429',
		'typography_body' => array(
			'family' => 'Open Sans',
			'style'  => '400',
			'size'   => '14',
			'line_height'=>'2.15',
			'letter_spacing' => '0px',
		),
		'body_text_color'=>'#777777',
		'body_background_color' => '#fff',
		'page_sidebar_layout' => 'sidebar-right',
		'content_controls' => array('padding-top' => 120,'padding-bottom' => 120),
		'typography_menu' => array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '18',
			'line_height'=>'26px',
			'letter_spacing' => '0px',
		), 
		'mainnav_color'		=> '#fff',
		'mainnav_hover_color'=>'#FF4040',
		'menu_distance_between' => 18,
		'typography_sub_menu' => array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '16',
			'line_height'=>'24px',
			'letter_spacing' => '0px',
		),
		'sub_nav_color'		=>'#000',		
		'sub_nav_color_hover'	=>	'#FF4040',
		'sub_nav_background'=>'#fff',
		'sub_nav_background_hover'=>'rgba(255, 255, 255, 0)',
		'sub_nav_border_color' => 'rgba(0, 0, 0, 0.1)',
		'typography_headings'	=> array(
			'family' => 'Jost',
			'style'  => '700',
			'line_height'=>'1.235',
			'letter_spacing' => '0px'		
		),
		'h1_size' => 72,
		'h2_size' => 36,
		'h3_size' => 32,
		'h4_size' => 24,
		'h5_size' => 18,
		'h6_size' => 16,
		'typography_blockquote' => array(
			'family' => 'Open Sans',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'30px',
			'letter_spacing' => '0px',
		),	
		'typography_blog_post_title' => array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '32',
			'line_height'=>'1.4',
			'letter_spacing' => '0',
		),
		'typography_blog_post_meta' => array(
			'family' => 'Open Sans',
			'style'  => '400',
			'size'   => '14',
			'line_height'=>'1.5',
			'letter_spacing' => '0px',
		),
		'typography_blog_post_buttons' => array(
			'family' => 'Jost',
			'style'  => '500',
			'size'   => '14',
			'line_height'=>'1',
			'letter_spacing' => '0',
		),
		'typography_blog_single_title' => array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '32',
			'line_height'=>'1.4',
			'letter_spacing' => '0px',
		),
		'typography_blog_single_comment_title' => array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '36',
			'line_height'=>'1.2',
			'letter_spacing' => '0px',
		),
		'typography_sidebar_widget_title' => array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '18',
			'line_height'=>'1.2',
			'letter_spacing' => '0px',
		),	
		'typography_footer_widget_title' => array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '18',
			'line_height'=>'1.5',
			'letter_spacing' => '0px',
		),	
		'typography_page_title'	=> array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '72',
			'line_height'=>'1.2',
			'letter_spacing' => '-0px',
		),
		'page_title_background_color' => '#222429',
		'page_title_background_color_opacity' => '100',
		'page_title_text_color' => 'rgba(255,255,255,1)',		
		'page_title_controls' => array('padding-top' => 288, 'padding-bottom' => 163),
		'page_title_background_image' => '',
		'page_title_image_size' => 'cover',
		'page_title_heading_enabled' => 1,
		'typography_breadcrumb'	=> array(
			'family' => 'Jost',
			'style'  => '400',
			'size'   => '18',
			'line_height'=>'1.5',
			'letter_spacing' => '0px',
		),
		'bread_crumb_prefix' =>'',
		'breadcrumb_separator' =>  wp_kses( '<i class="fa fa-angle-right"></i>', themesflat_kses_allowed_html() ),
		'breadcrumb_color' => 'rgba(255,255,255,1)',
		'typography_buttons' => array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '14',
			'line_height'=>'1',
			'letter_spacing' => '0px',
		),
		'typography_pagination'	=> array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '14',
			'line_height'=>'1',
			'letter_spacing' => '0px',
		),		
		'typography_bottom_menu' => array(
			'family' => 'Jost',
			'style'  => '400',
			'size'   => '18',
			'line_height'=>'1.5',
			'letter_spacing' => '0px',
		),
		'breadcrumb_enabled' => 1,
		'show_post_paginator' => 0,
		'blog_grid_columns' => 2,
		'post_content_elements' => 'meta,title,excerpt_content,readmore',
		'meta_elements' => 'author,comment,date',
		'blog_archive_exclude' => '',
		'blog_featured_title' => '',
		'sidebar_layout' => 'sidebar-right',
		'blog_archive_layout' => 'blog-list',
		'related_post_style'	=> 'blog-grid',
		'grid_columns_post_related' => 2,
		'number_related_post' => 2,
		'blog_sidebar_list'		  => 'blog-sidebar',	
		'blog_archive_readmore' => 1,
		'blog_archive_post_excepts_length' => 47,
		'blog_archive_readmore_text' => 'Read More +',
		'blog_archive_pagination_style' => 'pager-numeric',
		'blog_posts_per_page'	=> 3,
		'blog_order_by'	=> 'date',
		'blog_order_direction' => 'DESC',
		'page_sidebar_list'	=> 'blog-sidebar',	
		'portfolio_slug' => 'portfolios',
		'portfolio_name' => 'Portfolios',
		'portfolio_show_filter' => 0,
		'portfolio_grid_columns' => 3,
		'portfolios_number_post'=> 9,
		'portfolio_filter_category_order' => '',
		'portfolio_order_by' => 'date',
		'portfolio_order_direction' => 'DESC',
		'portfolio_exclude' => '',
		'portfolios_layout' => 'fullwidth',
		'portfolios_show_post_navigator' => 0,
		'portfolios_show_related' => 0,
		'portfolios_related_grid_columns' => 3,
		'portfolios_sidebar_list' => 'themesflat-custom-sidebar-portfoliosidebar',
		'number_related_post_portfolios' => 3,
		'portfolios_featured_title' => '',
		'project_slug' => 'project',
		'project_name' => 'Project',
		'project_show_filter' => 0,
		'project_grid_columns' => 3,
		'project_number_post'=> 9,
		'project_filter_category_order' => '',
		'project_order_by' => 'date',
		'project_order_direction' => 'DESC',
		'project_exclude' => '',
		'project_layout' => 'fullwidth',
		'project_show_post_navigator' => 0,
		'project_show_related' => 0,
		'project_related_grid_columns' => 3,
		'project_sidebar_list' => 'blog-sidebar',
		'project_featured_title' => '',
		'number_related_post_project' => 3,
		'services_slug' => 'services',
		'services_name' => 'Services',
		'services_show_filter' => 0,
		'services_grid_columns' => 2,
		'services_number_post'=> 6,
		'services_archive_pagination_style' => 'pager-numeric',
		'services_filter_category_order' => '',
		'services_order_by' => 'title',
		'services_order_direction' => 'DESC',
		'services_exclude' => '',
		'services_layout' => 'sidebar-right',
		'services_sidebar_list' => 'themesflat-custom-sidebar-servicessidebar',
		'services_show_post_navigator' => 0,
		'services_show_related' => 0,
		'services_related_grid_columns' => 3,
		'number_related_post_services' => 3,
		'services_featured_title' => '',
		'typography_footer' => array(
			'family' => 'Jost',
			'style'  => '400',
			'size'   => '14',
			'line_height'=>'1.5',
			'letter_spacing' => '',
		),
		'footer_background_color'	=> '#222429',
		'footer_title_widget_color' => '#ffffff',
		'footer_text_color'			=> '#FFFFFFB2',
		'footer_text_color_hover'   => '#FF4040',
		'footer_widget_areas' => 4,
		'footer_controls' => array('padding-top' => 115, 'padding-bottom' => 70),
		'footer1' => 'footer-1',
		'footer2' => 'footer-2',
		'footer3' => 'footer-3',
		'footer4' => 'footer-4',
		'footer_background_image' => '',
		'footer_image_size' => 'cover',
		'typography_bottom_copyright' => array(
			'family' => 'Jost',
			'style'  => '600',
			'size'   => '14',
			'line_height'=>'1.5',
			'letter_spacing' => '',
		),
		'bottom_background_color'	=> '#1C1E22',
		'bottom_text_color'			=> '#ffffff',
		'bottom_link_color'         => '#FF4040',
		'bottom_text_color_hover'   => '#ffffff',		
		'layout_version'			=> 'wide',		
		'footer_copyright'			=> 'Copyright © 2022 The Bixos - Business & Digital Agency WordPress Theme. Designed by <a href="https://themeforest.net/user/themesflat/portfolio">Themesflat</a>',
		'enable_smooth_scroll'	=> 0,
		'enable_preload' => 1,
		'preload' => 'preload-6',
		'page_title_styles' => 'default',
		'page_title_alignment' => 'center',
		'page_title_video_url' => '',		
		'show_action_box'	=> 0,
		'heading_action_box'	=>	'',
		'text_action_box'	=>	'',
        'text_button_action_box'	=> 'Read More',
        'action_box_background_image' => '',
        'action_box_background_color' => 'rgba(29, 42, 55, 0.9)',
        'action_box_heading_color' => '#ffffff',
        'action_box_text_color'	=> '#ffffff',
        'action_box_button_text_color' => '#ffffff',
        'action_box_button_background_color' => '#eb6d2f',
        'show_partner'	=> 0,
		'img_partner' =>'',
		'show_number_img_partner_desktop' => 6,
		'show_number_img_partner_tablet' => 4,
		'show_number_img_partner_mobile' => 2,
		'gap_img_partner' => 75,
		'partner_box_controls' => array('padding-top' => 97,'padding-bottom' => 97),
		'partner_box_background_color' => '#FF4040',
        //Woo
        'shop_products_per_page' => 9,
        'shop_columns' => 3,
        'shop_layout' => 'sidebar-right',
        'shop_layout_single' => 'fullwidth',
        'related_products' => 1,
        'related_products_columns' => 4,
        'product_featured_title' => '',
        'product_style' => 'product-style1'
	);
	return $default[$key];
}